sudo: required
language: python
python:
- 3.6
services:
- docker
stages:
- test
- deploy
jobs:
  include:
  - stage: test
    name: test-local-ubuntu
    env: DOCKER_SH="docker exec -t backup-test bash -vxc" DOCKER_IMAGE=ubuntu:disco
      PYTHON=python3.7 MAKE="make" AWS_DEFAULT_REGION=eu-central-1
    script:
    - sh -vx ./build-script/docker_start.sh
    - sh -vx ./build-script/before_script.sh
    - $DOCKER_SH "PYTHON=$PYTHON ./build-script/ubuntu_container_prep.sh"
    - $DOCKER_SH "$MAKE lint pytest PYTHON=$PYTHON"
  - name: test-functional-alpine
    env: DOCKER_SH="docker exec -t backup-test sh -vxc" DOCKER_IMAGE=alpine:latest
      PYTHON=python3.7 MAKE="make --trace" AWS_DEFAULT_REGION=us-east-2
    script:
    - sh -vx ./build-script/docker_start.sh
    - sh -vx ./build-script/before_script.sh
    - $DOCKER_SH "PYTHON=$PYTHON ./build-script/alpine_container_prep.sh"
    - $DOCKER_SH "$MAKE behave PYTHON=$PYTHON AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION SHELLCHECK=/bin/true"
    - $DOCKER_SH "set +vx; source aws_credentials.env; set -vx ;
      export AWS_REGION AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY;
      $MAKE doctest PYTHON=$PYTHON AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION SHELLCHECK=/bin/true"
  - stage: deploy
    script:
    - sh -vx ./build-script/before_deploy.sh
    - true
    deploy:
      provider: releases
      prerelease: true
      body: automated release created by travis - test in your usage scenario before
        deploying
      api_key:
        secure: PLa0iJ8lfrYdudMyYTYOJ633idoe4HKuxFxxF0UaEdueb6sRBPsWw47gY7JItk5UvFX3gSK//hQU6Bd0Yq9o3O9Qo4+FSQvmCqK+Pzop/eu1yoBO73cZPQdXA48GRdXHetsXRG6ZJIHVYoa4hIDUXrjRnPMx+6NZ8UeJ+9+N+H2tHaObAb6ct/uJfmyeQ5KQqIwRMmFX92eIxkNJfU96sxbN/XueHPL+60qIgNArVmYKhQ5NJ3Tfng+CLCtvsVb4lZKV6Ndb5GRuu3u+89Fjw1PMjNrpBLAePU+T0UxjAtjkO/CFjNHVau+sxObW2Pjbl6Qgc5o44xwewUcYWODT37GWT+6oUW85zTGX/zzaE6mA4CRKzaDwX2TBZj5RrUZxq+dzLZmOlm4QyJTSQa3tJzfOotl4N7mmVd2v7iGVeow9930fVgydJ7S20fyV5r8hgfbVkD2qWNA5tN8IYdMCz43ZkR33fTUsCpWUT5q87yKeFBjpXarMxg5YvCbN/0vOoqPN6XioVlj4O/YyguUO/juaeiohYluQR2LmLfahcVz7QPq342JKrqkK5qAYb3eJuaG6r1/7cZw3JpH1VQZYMHHi1nvQGFugdRnSD9ca028J+zxa3rjV+KtA6J397h/xBlDVdfQouD7uNKHfNkmiaDTO+jwKhXyiMaagtjm0xCI=
      file: dist/backup_cloud-0.3.tar.gz
      on:
        repo: backup-cloud/backup-base
        branch: tested
branches:
  only:
  - "/unreviewed.*/"
  - tested
  - "/devel.*/"
  - "/trial.*/"
