sudo: required
language: python
python:
- 3.6
services:
- docker
stages:
- test
- deploy
jobs:
  include:
  - stage: test
    name: test-local-ubuntu
    env: DOCKER_SH="docker exec -t backup-test bash -vxc" DOCKER_IMAGE=ubuntu:latest
      PYTHON=python3.6 MAKE="make" AWS_DEFAULT_REGION=eu-central-1
    script:
    - sh -vx ./build-script/docker_start.sh
    - sh -vx ./build-script/before_script.sh
    - $DOCKER_SH "PYTHON=$PYTHON ./build-script/ubuntu_container_prep.sh"
    - $DOCKER_SH "$MAKE lint pytest PYTHON=$PYTHON"
  - name: test-functional-alpine
    env: DOCKER_SH="docker exec -t backup-test sh -vxc" DOCKER_IMAGE=alpine:latest
      PYTHON=python3.6 MAKE="make --trace" AWS_DEFAULT_REGION=us-east-2
    script:
    - sh -vx ./build-script/docker_start.sh
    - sh -vx ./build-script/before_script.sh
    - $DOCKER_SH "PYTHON=$PYTHON ./build-script/alpine_container_prep.sh"
    - $DOCKER_SH "$MAKE behave PYTHON=$PYTHON AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      SHELLCHECK=/bin/true"
    - $DOCKER_SH "source aws_credentials.env; export AWS_REGION AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY; $MAKE doctest PYTHON=$PYTHON AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      SHELLCHECK=/bin/true"
  - stage: deploy
    script:
    - sh -vx ./build-script/before_deploy.sh
    - true
    # deploy:
    #   provider: releases
    #   api_key:
    #     secure: WmdoLzadtghtwsI03TrXMjaQVmWzmZRixa/7eCYXkuKfvf6lTK1ltTaHsnJUEoy/5eF9WceQj2BiYWfW3yp3g/WOsAc2vSxhQb9uhzZUiG1PQNeVlLeMdYhiOVeEZxfKtIV+Xt8Q/izlsFuM+MIdBA1AQ0FywSJSVYQ+dP8CNzMpF5PhIzet5Qm+EsH15xJAcoS4QxI6TM8AFbWjX94O1eGfr9u+kLK+uzeH5oCzJGNd+v5BqADtAmHqSMBw8iFCvNkjuYrei5sKl2uTSu36hY5tEOQueR91SVBABhMiezz7BG2sA6gQckDspB2Ya1drvd4UEPHIBLZq3ad6G+OCudK9ExM346p3Oj1LoTm90WZ3jVUXRTj6GKEix1vJaTNpwrTc4IqcZgdr1N946zzGGqI94u9OBAEhIiXh+Ibym+7ba4B0kCO3oZODDBYccmymc3gcxKp57cz5bajJLXU00LtX3tWVyTWfttBcVyxKnxTLhdVEjryeG4IZpJZ01pFtJjtoAwM9fTRWCXmxg+VDm66NhUJd/wvEicETDNnlvemL9RBXt8DlmP1jJmkd0V8I52VQkyTEylXHYpreBaa+5S0udsOuPrK5d+reap6ntH1Hab/VLMyWtItpTuSPpi+UYAWMH3m0FLZaBgefePL+YWHtMPRHEOsWJG8PJh52ZOY=
    #   file: dist/backup_cloud-0.1.tar.gz
    #   skip_cleanup: true
    #   on:
    #     all_branches: true
    #     condition: "$TRAVIS_BRANCH =~ ^tested$"
branches:
  only:
  - "/unreviewed.*/"
  - tested
  - "/devel.*/"

deploy:
  provider: releases
  api_key:
    secure: BTpOxtOvWnuousg8z7PkvBWSfvdCBHuHH8mZDlln2LCxDNiuUSYmwArO4rw3k8w3+P/uehn0DtjILuXc5NMIgzE6nETtChDTLvthvmoT4ESQuW0g5PIRSlAfUt/P5YFqMN8P692D6qBipjD9LLAKkz8DRGJth4eClT4a+FbginAFalwqqOp2aUbAcYvf32fFKKuO7tASrD1N7UxY6LxKX/7IWSzxKGnNOzr/W6J0vaMpmVWzH8hxTiDwBatBU5PGUnwWz5DFmxvgbjvDrLh0sQHt5FL8RUNdMr/fG20nHStoBMfWpw7UGNUaCUz7rzvOWWDE775XCh4AL2+wXBBvWH41S47Eli5Og9dCtns4b11nwgOTGuo36/SO/ffrtM2Va/SScUP3pQRvBZyFw6JseFd3wnOhSFClrumrziiFdUryXPUxai4ZL5aVoL2zZG2+IpTwqgAqCZj63ZnvNemEUY3RzobmiJEhOLdovJvQ4yR7vJVXFUWFNWfNqbWFw+BOif0kL8n9XM//DdQjGPYvpyb0HvF56BWPxxQ0bz15Xr53fPLaaB3/kJDC4RbIKZ6VccwFqsnoav5mfPx2ZLqXX7vHUgl+jNfMvSfOnp3JoU2wD4YIIHFoct4jAgWX1hHyxkNlvjFNoUS/yro7SS5ioggnZWZvxmTShQlhu/3nZMM=
  file: dist/backup_cloud-0.1.tar.gz
  on:
    repo: michael-paddle/backup-base
    branch: tested
