---
sudo: required

language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

branches:
  only:
    - /unreviewed.*/
    - tested
    - /devel.*/

before_script:
  - sudo add-apt-repository ppa:ansible/ansible-2.6 -y
  - sudo apt-get update
  - sudo apt-get install python3-pip shellcheck ansible python3-gpg shellcheck
  - pip3 install -r dev-requirements.txt
  - sudo pip2 install -r dev-requirements.txt
  - openssl aes-256-cbc -K $encrypted_c2402a3ad637_key -iv $encrypted_c2402a3ad637_iv -in aws_credentials_travis.yml.enc -out aws_credentials_travis.yml -d
  - echo $test_random_key > .anslk_random_testkey

script:
  - "make prepare_travis"
  - "make test"
  - rm aws_credentials_travis.yml

after_script:
  - openssl aes-256-cbc -K $encrypted_a45cc096e026_key -iv $encrypted_a45cc096e026_iv -in deploy_key.enc -out deploy_key -d
  - chmod 400 deploy_key
  - ./push_on_success.sh
  - rm deploy_key
  
