---
#
#  This is based on the lambda and lambda policy testcases out of Ansible's integration tests
#
#  As such it is licensed under the GPLv3 with copyright belonging to various including:
#
#  * Michael De La Rue
#  * William Thames
#  * The Ansible Project
#
#  Further work on this done as paid work by Michael De La Rue for paddle.com.
#

- hosts: localhost
  vars:
    credentials_file: "aws_credentials_{{aws_account_name}}.yml"
    aws_account_name: michael
    test_key: "{{ lookup('password', '.anslk_random_testkey chars=ascii_lowercase,digits length=15') }}"
  vars_files:
    # the following isloaded with include_vars so it can appear after we
    # have started
    # - "{{ backup_credentials_file }}" 
    - "{{ credentials_file }}"
  roles:
    - test_enc_backup
