---
#
#  This adds IAM requirements to allow the deployment script to be
#  run.  Since it creates and modifies IAM users roles and policies it
#  needs to be run with full IAM account manager privilages.
#

- hosts: localhost
  vars:
    ansible_connection: local
    backup_test_user: "backup_tester"
    aws_account_name: michael
  vars_files:
    - "aws_credentials_{{aws_account_name}}_iam_admin.yml"
  roles:
    - test_account

